FROM codercom/code-server:latest

USER root

# Install Python 3 and Pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install required telemetry libraries
# Using --break-system-packages for this lab environment to ensure simplicity
RUN pip3 install requests splunk-sdk --break-system-packages

USER coder
